// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMq8Yx9LMtBffEBb-BUFGml1ZsZf7ZvFg',
    appId: '1:115685872342:web:ce78d38c7aaae14fcbaf77',
    messagingSenderId: '115685872342',
    projectId: 'weidan-ecom',
    authDomain: 'weidan-ecom.firebaseapp.com',
    storageBucket: 'weidan-ecom.firebasestorage.app',
    measurementId: 'G-92YETLXKST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFNzmpliBoPFOq2dfLuvoAh7qfTm1NGQ',
    appId: '1:115685872342:android:77a04563fa0c1b78cbaf77',
    messagingSenderId: '115685872342',
    projectId: 'weidan-ecom',
    storageBucket: 'weidan-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJl7YUblPuiRdvJv-W-lTCGULXQhLMBn0',
    appId: '1:115685872342:ios:df13c9a5fd4dfd85cbaf77',
    messagingSenderId: '115685872342',
    projectId: 'weidan-ecom',
    storageBucket: 'weidan-ecom.firebasestorage.app',
    iosBundleId: 'com.example.weidanEcomQF1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJl7YUblPuiRdvJv-W-lTCGULXQhLMBn0',
    appId: '1:115685872342:ios:df13c9a5fd4dfd85cbaf77',
    messagingSenderId: '115685872342',
    projectId: 'weidan-ecom',
    storageBucket: 'weidan-ecom.firebasestorage.app',
    iosBundleId: 'com.example.weidanEcomQF1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMq8Yx9LMtBffEBb-BUFGml1ZsZf7ZvFg',
    appId: '1:115685872342:web:8ead77c714b7c539cbaf77',
    messagingSenderId: '115685872342',
    projectId: 'weidan-ecom',
    authDomain: 'weidan-ecom.firebaseapp.com',
    storageBucket: 'weidan-ecom.firebasestorage.app',
    measurementId: 'G-TG4LRKMET2',
  );
}
